gha-runner-scale-set:
  githubConfigUrl: "https://github.com/com-nimeji/sim-devastation"
  githubConfigSecret: gh-token-secret
  containerMode:
    type: "dind"
  maxRunners: 4
  controllerServiceAccount:
    namespace: gha-runner-scale-set-controller
    name: gha-runner-scale-set-controller-gha-rs-controller
