apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gh-token-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        github_token: {{` "{{ .github_token }}" `}}
  data:
    - secretKey: github_token
      remoteRef:
        key: /apps/sim-devastation
        property: github_token
