apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  namespace: {{ .Release.Namespace }}
  labels:
    app: n8n
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - n8n.nimeji.com
      secretName: n8n-tls
  rules:
    - host: n8n.nimeji.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 80
