apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-db
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: n8n-db
  data:
    - secretKey: password
      remoteRef:
        key: /n8n/db
        property: password
